### ISSUE TITLE
plugins: remove class dependency, refactor plugin export

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#252]
```
export default {
  Component: MyPluginComponent
  name: 'example/content/my-plugin'
  version: '0.0.1'
  icon: <StarIcon />
  text: 'Icon'
}
```

**Comment by arekkas** [comment]
I think it would be better if the hooks where not defined there, but rather in the react component - because then they would have access to the properties natively and we would not have to pass them down. What do you think @inyono ?

**Comment by inyono** [comment]
I don't think that this makes much sense. IMHO, the hooks are on a whole different layer. E.g., they aren't executed when the component is rendered. Furthermore, we don't have access to the mounted component when the hooks are executed. So we would have to instantiate a React component to use the props (and have to pass to it the props, too).

**Comment by arekkas** [comment]
> I don't think that this makes much sense. IMHO, the hooks are on a whole different layer. E.g., they aren't executed when the component is rendered. Furthermore, we don't have access to the mounted component when the hooks are executed. So we would have to instantiate a React component to use the props (and have to pass to it the props, too).

This makes partially sense. We have currently two types of hooks:

* serialize/unserialize
* handleXYZ (handleUndo, handleRemoveKey)

The first class is used outside of component lifecycle, whilst the second isn't. And the second class would need access to the properties of that cell.

However, there is another problem. strg+z is independent of the currently focused cell, you can focus a cell and strg+z something on the other end of the page. That means it will be very difficult to find the cell that the undo operation will take place at - we have to basically inspect the action or something. Nasty.

**Comment by arekkas** [comment]
I think it makes also sense in a scenario where the handleXYZ thing needs access to a DOM reference, or similar. I think this works at the moment too, but has some trickery involved.

**Comment by arekkas** [comment]
Another use case is where ``handleXYZ` need access to a DOM ref inside the plugin. I think there are two possibilities here:

1. Move the handle* things to the component
2. Change the signature of *handle funcs to: `(event: Event, props: PluginProps, component: Component)`

In both cases, we need a registry that maps a unique id to a react component instance. It would allow us to create side effects easily:

```
({id}: action) => {
  const component = lookup(id)
  const handleFocusNextHotKey(.., .., component)
}
```

**Comment by arekkas** [comment]
Additionally I think that plugins should be allowed to export a reducer for the cell state, it would allow us to do something like this:

```
const pluginReducer = (state, action) => {
  if (action.type === 'UNDO') {
    const newState = { ...state }
    state.content.plugin.state.editorState = state.content.plugin.state.editorState.apply()
    return newState
  }
}
```

Of course, this is a very speific requirement. Basically, it's a proposed bug fix for slate undo/redo. I'm not sure if it would be beneficial to normal plugins and if we should add this complexity.

**Comment by inyono** [comment]
> The first class is used outside of component lifecycle, whilst the second isn't. And the second class would need access to the properties of that cell.
True, I didn't think about the second case. Props are now problem, because we can pass them form reducers, too. Or do we need access to more stuff that is not in the state.

Overall, I'm not sure what to do about this. IMHO, it would be weird if the first case is covered in the component directly (and we would need to instantiate the React component in the reducer) while 
it is also true that the second case might be better covered in the component.

> However, there is another problem. strg+z is independent of the currently focused cell, you can focus a cell and strg+z something on the other end of the page. That means it will be very difficult to find the cell that the undo operation will take place at - we have to basically inspect the action or something. Nasty.

Not so sure what you mean? Don't we track which cell is focused in our store?

> Another use case is where `handleXYZ need access to a DOM ref inside the plugin.

You can also do this with hooks not defined in the component by passing the ref to onChange.

> Move the handle* things to the component
Change the signature of *handle funcs to: (event: Event, props: PluginProps, component: Component)
In both cases, we need a registry that maps a unique id to a react component instance. It would allow us to call side effects easily with all necessary information:

Not sure if this is a good approach if you want to do this in the reducer (because of those effects). It *might* be okay if we save the instance in the store but even then there *might* be issues when `handleXYZ` is not pure...

> Additionally I think that plugins should be allowed to export a reducer for the cell state, it would allow us to do something like this:

Isn't that what the hooks are doing already? We need to find out to which plugin/component/whatever we need to pass the action anyway, so this approach is not much different from defining hooks, is it? Further more, plugin authors would need to understand redux to some degree, wouldn't they?

**Comment by arekkas** [comment]
We could also do something like this, what do you think @inyono ?

```
import { Component } from 'react'

class MyFooPlugin extends Component {
  // render() 

  onFocus()
  onBlur()
  onUndo()
  // on...
}

MyFooPlugin.config = {
  name, version
  hooks
}
```

**Comment by arekkas** [comment]
ping @inyono

**Comment by inyono** [comment]
Yeah, let's give it a shot (not 100% convinced but seems like a sound plan)

**Comment by arekkas** [comment]
@inyono I think that, at least for functional components, this doesn't make a lot of sense, because we do not have access to `this` and `this.props`:

```jsx
const MyFooPlugin = () => (<div />)

MyFooPlugin.someCallback = () => {
  console.log(this) // undefined
}
```

So we would probably still have to pass down props and so on. Thus I'm not sure if any of the ideas proposed make that much sense. Maybe it's better to try and pass as much information as possible instead and separate the react component from the plugin config. However, I think it is important that the developer has access to the props, maybe the dom element.
