### ISSUE TITLE
plugins: introduce toolbars with decorators?

### ISSUE THREAD

**Issue by bkniffler** [ory-am/editor#289]
Hi, 
Awesome stuff here. Have you had any thoughts to have toolbars for blocks?
The best solution I could come up with was to have a decorator for your blocks. A decorator could also make props like isFocused available. Check out https://github.com/bkniffler/slate-mate, there is an `Example Youtube block` in the readme.md. 

The toolbar styles of http://globocom.github.io/megadraft/#/?_k=6j5myx is pretty nice.

What are your thoughts on this?

**Comment by arekkas** [comment]
Hey, just to make sure we're on the same page: With blocks, do you mean [cells](https://ory-am.gitbooks.io/ory-editor/content/#how-it-works)?

Regarding toolbars: We do not have a policy that dictates how you use toolbars. We provide a default toolbar component that is used for the slate plugin (the one on the bottom) and have the right toolbar which is controlled by the editor, because there you can select plugins and stuff.

So actually, you're absolutely free to solve the toolbar problem any way you want in your plugin. It could be done with decorators or any other type of technology. Of course it would be interesting to provide a few default decorators for some generic toolbars or similar stuff.

Megadraft looks really interesting, I didn't know that project exists!

**Comment by arekkas** [comment]
this is now solved by #318 and thus superseded
