### ISSUE TITLE
build: remove extravaganza from build and make build compatible with create-react-app

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#295]
I think we should remove all of the extra build steps that we are doing (like react-css-modules) so that it becomes possible to compile the bundle using create-react-app. This way, it would be possible to include internal source files from the editor in create-react-apps: `import foo from 'ory-editor/src/editor/service/...`.

Additionally it might be interesting to transpile individual source files to es5 syntax using `babel --lib`, without combining them in a single build file. Similar to how most react npm modules solve it ([example](https://github.com/chrisui/react-hotkeys/blob/master/build/npm/lib/HotKeys.js)). We would probably have to remove flow for that first, and probably also include the css?

What do you think @inyono ?

**Comment by inyono** [comment]
> I think we should remove all of the extra build steps that we are doing (like react-css-modules) so that it becomes possible to compile the bundle using create-react-app. This way, it would be possible to include internal source files from the editor in create-react-apps.

Not sure what you mean? I don't see the advantage (apart from the fact that we don't have to keep the fork updated ofc).

> Additionally it might be interesting to transpile individual source files to es5 syntax using babel --lib, without combining them in a single build file. Similar to how most react npm modules solve it (example). We would probably have to remove flow for that first, and probably also include the css?

Nope, shouldn't be needed. There exists a babel transform that [strips flow-types](https://babeljs.io/docs/plugins/transform-flow-strip-types/), so no need for Webpack there. But CSS is still problematic and probably has to be stubbed so that Babel doesn't fail (and needs an external building step)
