### ISSUE TITLE
karma: IE launcher does not work

### ISSUE THREAD

**Issue by arekkas** [ory-am/editor#6]
upstream https://github.com/karma-runner/karma-ie-launcher/issues/36

**Comment by inyono** [comment]
Just because the question kinda arises in flitt too: Does it even make sense to launch karma for different browsers for every kind of test? At least I see no real reason to do this for the unit test suite, since it slows the process down greatly, and there should be no remarkable difference in the JS implementations (given Babel and/or Polyfills). I only see advantages for other types of tests, but do we run those through karma resp. do we run those together with the unit tests, usually?

**Comment by arekkas** [comment]
Good questions, I think it should be enough to have e2e run in every browser. We should definitely check out https://saucelabs.com which runs e2e tests on all platforms.

**Comment by tacurran** [comment]
I would suggest an e2e test suite for safari, chrome and ie on web and mobile. Will we need to support FF, Opera, and others ? Lets set up a minimum responsibility using for instance Saucelabs Manual Testing +1:  to at  least make customers aware of any known issues.  Not sure about protractor.

**Comment by arekkas** [comment]
Yes, we need to support all major browsers: FireFox, Chrome, Edge, Safari. I haven't really looked into any of the e2e test frameworks but @inyono is currently looking into them for flitt.
